# Generated by Django 4.1.7 on 2023-10-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('teacher', models.CharField(max_length=100)),
                ('year', models.IntegerField(max_length=2)),
                ('room', models.IntegerField(max_length=10)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
