# Generated by Django 4.1.7 on 2023-10-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='year',
            field=models.IntegerField(),
        ),
    ]
