# Generated by Django 4.2.6 on 2023-10-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_timetable_room_alter_timetable_year'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timetable',
            table='timetable',
        ),
    ]
