# Generated by Django 4.1.7 on 2023-11-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_timetable_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='color',
            field=models.CharField(default='Red', max_length=50),
        ),
        migrations.AddField(
            model_name='timetable',
            name='name',
            field=models.CharField(default='Operating System', max_length=100),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
