# Generated by Django 4.2.6 on 2023-10-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historyy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('teacher', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('room', models.IntegerField()),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
