# Generated by Django 4.2.6 on 2023-11-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0004_historyy_color_historyy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('teacher', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('room', models.IntegerField()),
                ('time', models.CharField(max_length=50)),
                ('color', models.CharField(default='red', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
